# fly.toml app configuration file generated for wouters-n8n on 2026-01-30T18:32:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wouters-n8n'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  EXECUTIONS_DATA_MAX_AGE = '48'
  EXECUTIONS_DATA_PRUNE = 'true'
  EXECUTIONS_DATA_PRUNE_MAX_COUNT = '1000'
  GENERIC_TIMEZONE = 'Europe/Amsterdam'
  N8N_LISTEN_ADDRESS = '0.0.0.0'
  N8N_PORT = '8080'
  N8N_PROTOCOL = 'https'
  NODE_ENV = 'production'

[mounts]
  source = "n8n_vol"
  destination = "/home/node/.n8n"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
