# fly.toml app configuration file generated for wouters-n8n on 2026-01-30T18:48:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wouters-n8n'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  EXECUTIONS_DATA_MAX_AGE = '48'
  EXECUTIONS_DATA_PRUNE = 'true'
  EXECUTIONS_DATA_PRUNE_MAX_COUNT = '1000'
  GENERIC_TIMEZONE = 'Europe/Amsterdam'
  N8N_HOST = 'https://wouters-n8n.fly.dev/'
  N8N_LISTEN_ADDRESS = '0.0.0.0'
  N8N_PORT = '80'
  N8N_PROTOCOL = 'https'
  NODE_ENV = 'production'
  WEBHOOK_URL = 'https://wouters-n8n.fly.dev/'

[[mounts]]
  source = 'n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
